"""calc_dalton"""
# hard-coding in protein sequence
PROTEIN_SEQUENCE = "MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQPTFCSHCT" \
                   "DFIWGFGKQGFQCQVCCFVVHKRCHEFVTFSCPGADKGPASDDPRSKHKFKIHT" \
                   "YSSPTFCDHCGSLLYGLIHQGMKCDTCMMNVHKRCVMNVPSLCGTDHTERRGRI" \
                   "YIQAHIDREVLIVVVRDAKNLVPMDPNGLSDPYVKLKLIPDPKSESKQKTKTIK" \
                   "CSLNPEWNETFRFQLKESDKDRRLSVEIWDWDLTSRNDFMGSLSFGISELQKAG" \
                   "VDGWFKLLSQEEGEYFNVPVPPEGSEGNEELRQKFERAKIGQGTKAPEEKTANT" \
                   "ISKFDNNGNRDRMKLTDFNFLMVLGKGSFGKVMLSERKGTDELYAVKILKKDVV" \
                   "IQDDDVECTMVEKRVLALPGKPPFLTQLHSCFQTMDRLYFVMEYVNGGDLMYHI" \
                   "QQVGRFKEPHAVFYAAEIAIGLFFLQSKGIIYRDLKLDNVMLDSEGHIKIADFG" \
                   "MCKENIWDGVTTKTFCGTPDYIAPEIIAYQPYGKSVDWWAFGVLLYEMLAGQAP" \
                   "FEGEDEDELFQSIMEHNVAYPKSMSKEAVAICKGLMTKHPGKRLGCGPEGERDI" \
                   "KEHAFFRYIDWEKLERKEIQPPYKPKARDKRDTSNFDKEFTRQPVELTPTDKLF" \
                   "IMNLDQNEFAGFSYTNPEFVINV"

NAME_SEQUENCE = "Protein kinase c beta type"

# creating program output
print("The length of " + NAME_SEQUENCE + " is: " + str(len(PROTEIN_SEQUENCE)))
print("The average weight of this protein sequence is: " + str(len(PROTEIN_SEQUENCE)*0.11))
